// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BtnVue: typeof import('./src/components/BtnVue.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon3bars: typeof import('./src/icons/icon-3bars.vue')['default']
    IconOk: typeof import('./src/icons/icon-ok.vue')['default']
    IconSetting: typeof import('./src/icons/icon-setting.vue')['default']
    IconTickCircle: typeof import('./src/icons/icon-tick-circle.vue')['default']
    IconXCircle: typeof import('./src/icons/icon-x-circle.vue')['default']
    PageVue: typeof import('./src/components/page-vue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollUp: typeof import('./src/components/scroll-up.vue')['default']
  }
}
